apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
    
  template.app-deployed: |
    email:
      subject: 🚀 Application {{.app.metadata.name}} deployed successfully
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version.
      
  template.app-health-degraded: |
    email:
      subject: 🚨 Application {{.app.metadata.name}} has degraded
    message: |
      {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} health is degraded.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
      
  template.app-sync-failed: |
    email:
      subject: ❌ Application {{.app.metadata.name}} sync failed
    message: |
      {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} sync failed.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
      
  trigger.on-deployed: |
    - description: Application is synced and healthy
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
      
  trigger.on-sync-failed: |
    - description: Application sync failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']

  subscriptions: |
    - recipients:
      - slack:cicd-alerts
      triggers:
      - on-deployed
      - on-health-degraded
      - on-sync-failed