apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "staging.club-platform.local,localhost"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"