"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from environ import Env
import sys

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경변수 세팅
env = Env()
env_path = BASE_DIR / ".env"
if env_path.exists():
    with env_path.open("rt", encoding="utf8") as f:
        env.read_env(f, overwrite=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '192.168.0.14',  # 현재 사용 중인 IP
    '192.168.0.4'
]


# Application definition

INSTALLED_APPS = [
    # ai chatbot
    'channels',
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    # 'dj_rest_auth.jwt_auth',  # 1
    'drf_yasg',
    'corsheaders',

    # project apps
    'club_account',
    'club_board',
    'club_introduce',
    'club_information',
    'club_management',
    'ai_chatbot',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# MySQL 설정 추가
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'gwnu_club_db'),
        'USER': os.environ.get('DB_USER', 'gwnu_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'gwnu_password'),
        'HOST': os.environ.get('DB_HOST', 'db'),  # 'localhost' 대신 'db' 사용
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # TCP/IP 연결 강제 사용
            'host': os.environ.get('DB_HOST', 'db'),
        }
    }
}

# 테스트 환경 설정
if 'test' in sys.argv:
    # 테스트용 데이터베이스 (메모리 사용)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
    
    # 테스트용 이메일 백엔드
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    
    # 빠른 비밀번호 해싱
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]
    
    # dj-rest-auth 테스트 설정
    ACCOUNT_EMAIL_VERIFICATION = 'none'
    ACCOUNT_EMAIL_REQUIRED = False
    ACCOUNT_AUTHENTICATION_METHOD = 'email'
    ACCOUNT_USERNAME_REQUIRED = False
    
    # REST Framework 테스트 설정
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework.authentication.TokenAuthentication',
            'rest_framework.authentication.SessionAuthentication',
        ],
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.IsAuthenticated',
        ],
        'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'  # 한국 표준시(KST)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For demo purposes only. Use a white list in the real world.
CORS_ORIGIN_ALLOW_ALL = True  # False

# CSRF 관련 설정
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://192.168.0.14:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.0.14:8000',
    'http://192.168.0.4:8000',
]
# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:3000', # react의 포트번호
#     'http://127.0.0.1:3000',
#     'http://localhost:8000', # django의 포트번호
#     'http://127.0.0.1:8000'
# )
# CORS_ALLOW_CREDENTIALS = True
# CSRF_TRUSTED_ORIGINS = (
#     'http://localhost:8000',
#     'http://127.0.0.1:8000',
# )

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_AUTH = {
    'SESSION_LOGIN': True,
    # 'USE_JWT': True,
    # 'JWT_AUTH_COOKIE': 'auth',
    # 'JWT_AUTH_HTTPONLY': False,
    'ACCOUNT_LOGOUT_ON_GET': True,

    'REGISTER_SERIALIZER': 'club_account.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'club_account.serializers.CustomUserDetailsSerializer',

}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.IsAdminUser',
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        # 'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 1 페이지당 보여줄 갯수
}

AUTH_USER_MODEL = 'club_account.CustomUser'
ACCOUNT_ADAPTER = 'club_account.adapters.CustomAccountAdapter'
# ALLAUTH's Account Configuration
SITE_ID = 1
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # email
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # none, Optional, mandatory
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/'  # 익명의 사용자 이메일 인증시 이동 url
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'  # 인증된 사용자 이메일 인증시 이동 url
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # 메일 호스트 서버
EMAIL_PORT = '587'  # gmail과 통신하는 포트
EMAIL_HOST_USER = env("EMAIL_HOST_USER")  # 발신할 이메일
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD") # 발신할 메일의 비밀번호
EMAIL_USE_TLS = True  # TLS 보안 방법
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 발신할 이메일
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # 유저가 받은 링크를 클릭하면 회원가입 완료되게끔
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1  # 이메일 유효기간
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""  # 이메일에 자동으로 표시되는 사이트 정보

ASGI_APPLICATION = 'backend.asgi.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}