# Generated by Django 4.2.1 on 2025-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0003_clubdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
