# Generated by Django 4.2.1 on 2025-07-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0004_allow_null_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
    ]
